[build-system]
requires = [
    "setuptools", 
]
build-backend = "setuptools.build_meta"

[project]
name = "dreamcoat"
description = "The joyful oceanographic seagoing expedition planning helper"
readme = "README.md"
classifiers =[
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Oceanography",
    "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = [
    "numpy>=2.4.6,<3",
    "geographiclib>=2.1,<3",
    "networkx>=3.6.1,<4",
    "scipy>=1.17.1,<2",
    "scikit-learn>=1.8.0,<2",
]
dynamic = ["version"]
requires-python = ">= 3.11"

[tool.setuptools.packages.find]
include = ["dreamcoat*"]

[tool.setuptools.dynamic]
version = {attr = "dreamcoat.meta.version_number"}

[tool.ruff]
line-length = 79

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
lines-after-imports = 2

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
dreamcoat = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
ipykernel = ">=7.2.0,<8"
pytest = ">=9.0.3,<10"
cartopy = ">=0.25.0,<0.26"
