name: Generate docs 
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Build and deploy docs
        run: |
          pip install mkdocs-material 
          mkdocs gh-deploy --force
      - name: Add and commit CNAME
        run: |
          echo "dreamcoat.hseao3.group" > CNAME
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add CNAME
          git commit -m "Create CNAME"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
