name: Run pixi tests 
on:
  push:
    paths:
      - .github/workflows/pixitests.yml
      - dreamcoat/**
      - tests/**
jobs:
  build:
    name: Build package and run tests
    strategy:
      matrix:
        python-version: ["3.14"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up pixi
      run: |
        wget -qO- https://pixi.sh/install.sh | sh
